---
title: Air Collective
baseURL: "/"
params:
  layout_style: overflow
  palette: blue
  header:
    title: Air Collective
    tagline: Breathing devices for everyone
    profile_img: "/images/aircollectivelogo.png"
    bg: light
    has_nav: true
    has_social: false
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
